/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hodart (https://sketchfab.com/hodart)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/spongebob-fish-incidental-70-1aee02c836334e7cab3640d5848f9185
Title: SpongeBob Fish - Incidental 70
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/spongebob.glb'

const Spongebob = ( { currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group);
  
  useEffect(() => {
      Object.values(actions).forEach((action) => action.stop());
      
      if(actions[currentAnimation]) {
        actions[currentAnimation].play();
      }
    }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="068aeaa59ac64d5f9c029acd3f22925afbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_33"
                      geometry={nodes.Object_33.geometry}
                      material={materials.material}
                      skeleton={nodes.Object_33.skeleton}
                    />
                    <skinnedMesh
                      name="Object_35"
                      geometry={nodes.Object_35.geometry}
                      material={materials.body}
                      skeleton={nodes.Object_35.skeleton}
                    />
                    <group name="Object_32" position={[0, 29.8, 12.733]} />
                    <group name="Object_34" position={[0, -29.8, -13.046]} />
                  </group>
                </group>
                <group name="eye_low" position={[0, 29.8, 12.733]} />
                <group name="body_low" position={[0, -29.8, -13.046]} />
                <group
                  name="cs_master"
                  position={[50, 1750, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={10}
                />
                <group
                  name="cs_square_2"
                  position={[50, 149.67, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={15.412}
                />
                <group name="cs_square" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="cs_hips"
                  position={[50, 1150, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={20.552}
                />
                <group
                  name="cs_circle"
                  position={[50, 450, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={20.552}
                />
                <group
                  name="cs_neck"
                  position={[50, 1450, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={20.552}
                />
                <group
                  name="cs_head"
                  position={[50, 1350, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={20.552}
                />
                <group
                  name="cs_shoulder_left"
                  position={[50, 1550, 0]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={103.843}
                />
                <group
                  name="cs_arm_fk"
                  position={[150, 850, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={82.209}
                />
                <group
                  name="cs_forearm_fk"
                  position={[250, 850, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={82.209}
                />
                <group
                  name="cs_sphere_012"
                  position={[350, 250, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={20.552}
                />
                <group name="cs_sphere" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="cs_hand"
                  position={[50, 1950, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={30.825}
                />
                <group
                  name="cs_shoulder_right"
                  position={[50, 1650, 0]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={103.843}
                />
                <group
                  name="cs_thigh_fk"
                  position={[50, 750, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={82.209}
                />
                <group
                  name="cs_calf_fk"
                  position={[50, 850, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={82.209}
                />
                <group
                  name="cs_foot"
                  position={[50, 1050, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={30.825}
                />
                <group
                  name="cs_foot_roll"
                  position={[50, 1250, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={59.158}
                />
                <group name="cs_foot001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="cs_foot_01"
                  position={[50, 1850, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={218.646}
                />
                <group name="cs_foot002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="cs_toe"
                  position={[50, 950, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={42.926}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Spongebob
